// Datos de Finca Palos Verdes — actualizado a agosto 2026
// Editar aquí para actualizar cualquier cifra del sitio. No hay que tocar el HTML.

const DATA = {
  meta: {
    fecha: "Agosto 2026",
    fx: "4.100 COP/USD",
    operador: "Construagro S.A.S. (NIT 860.520.662-7)",
  },

  resumen: {
    kpis: [
      { label: "Hato (cabezas)", value: "38", meta: "ene-2026 · pico 54 con machos", diff: "brief: 44" },
      { label: "Peso vivo total", value: "13,9 t", meta: "13.918 kg pesados feb-2025", diff: "brief: 16 t" },
      { label: "Preñez", value: "~45%", meta: "9/20 vientres", diff: "brief: 94%" },
      { label: "Ganancia diaria", value: "~0,5 kg/d", meta: "terneros 1,0–1,6 kg/d", diff: "brief: 0,90" },
      { label: "Precio res en pie", value: "$9.750/kg", meta: "venta real jul-2025", diff: "brief: $12.000" },
      { label: "Área", value: "18,2 ha", meta: "12,7 PV + 5,6 El Recuerdo · laguna 1,8", diff: "" },
      { label: "Empleados (planilla)", value: "1", meta: "Néstor Cañas · base $2,6M/mes", diff: "brief: 3" },
      { label: "Cert. orgánica", value: "Huerta", meta: "Mayacert 2023-034 · venció ago-2024", diff: "" },
      { label: "Sanidad ICA", value: "Libre Bruc.+TB", meta: "certs 24BR y 24TB · renovar 2025", diff: "" },
    ],
    alertas: [
      { nivel: "alta", titulo: "Certificación orgánica vencida", texto: "El sello Mayacert 2023-034 (huerta) venció el 16/08/2024. Renovar para sostener 'huerta orgánica certificada'.", fuente: "SEN-COV2 CONSTRUAGRO 2023.034" },
      { nivel: "alta", titulo: "El modelo base opera en déficit", texto: "Como negocio independiente, la operación actual NO se autofinancia: ingresos ~25–50M vs costos ~90–120M/año → déficit ~50–90M. El valor hoy está en el capital natural/social/inspiración + patrimonio (tierra ~4.328M, hato ~135M), no en la utilidad. La ronda debe crear la pata financiera, no escalar un negocio rentable.", fuente: "Análisis Modelo Base 4 Retornos" },
      { nivel: "alta", titulo: "Certificaciones sanitarias por renovar", texto: "Predio libre de brucelosis (ICA 0001270553-24BR, venció 05/08/2025) y de tuberculosis (ICA 0001270553-24TB, venció 12/07/2025). Reprogramar los muestreos Servigan (~$1,9M c/u) para renovar ambas.", fuente: "Certificados ICA brucelosis/tuberculosis" },
      { nivel: "alta", titulo: "Factura de energía en mora", texto: "Factura Enel/Codensa del predio Casa Blanca Cascajal con saldo en mora (~$5,6M). Poner al día.", fuente: "202410072150" },
      { nivel: "media", titulo: "Titularidad de la tierra a aclarar", texto: "En 2017 los predios eran de Construagro LTDA; en 2025 los prediales están a nombre de terceros (M.C. Gaviria / B.T. Vargas Gil). Reconstruir la cadena de titularidad.", fuente: "Informe 2017 · prediales 2025" },
      { nivel: "media", titulo: "Cifras del brief desalineadas con los registros", texto: "El brief publica 44 cab / 16 t / 94% / 0,90 kg/d; los registros dan 38 / 13,9 t / ~45% / ~0,5. Alinear antes de due diligence.", fuente: "reconciliacion.md" },
      { nivel: "media", titulo: "Sin chequeo de preñez 2026", texto: "El último chequeo con conteo es de feb-2025. Programar chequeo reproductivo 2026 para sostener cualquier % actual.", fuente: "Vacas_para_Descarte" },
      { nivel: "baja", titulo: "Línea porcina sin animales", texto: "El brief incorpora cerdos en 2026, pero los censos ICA muestran 0 porcinos. Toda la economía porcina es proyección.", fuente: "Tuberculosis Palos Verdes (censo)" },
      { nivel: "media", titulo: "Predial 2026 subirá (avalúo catastral)", texto: "El IGAC (Res. 20257/2025) incrementa el avalúo catastral rural para 2026; el impuesto predial de Palos Verdes y El Recuerdo aumentará. Presupuestarlo.", fuente: "Resolución 20257 de 2025 - IGAC" },
      { nivel: "media", titulo: "Riego eléctrico caro → oportunidad solar", texto: "La bomba de riego actual (25 HP eléctrica, 18,7 kW) cuesta ~$19.679/hora a $877/kWh. Hay un estudio de bombeo solar (ene-2025) que reduciría este costo y la mora con Enel.", fuente: "Bombeo Solar Finca Palos Verdes 2025.xlsx" },
      { nivel: "media", titulo: "Inversión right-sized: US$286k, no US$1M", texto: "El modelo costeado (cotizaciones reales) dimensiona la ronda en US$285.899 (~29% del brief), por fases. Break-even operativo Año 2, caja Año 3, EBITDA de crucero ~250M (20%). La Fase 2 (venue, 53% del ingreso) depende del uso de suelo POT — plan B sin venue = US$190k.", fuente: "Modelo de inversión costeado · Parte 2" },
      { nivel: "baja", titulo: "Oportunidad: créditos de carbono", texto: "En los archivos hay material del proyecto de ganadería regenerativa Carbono Local+ (Verra ID 3927, VCS+CCB, VM0042). Potencial 5ª línea de ingreso. Acción: confirmar si Palos Verdes está vinculada formalmente y bajo qué términos.", fuente: "Roll-up Carbono Local+ NP 2023" },
    ],
  },

  brief: {
    notaFundadora: "Estamos muy orgullosos y felices con lo que hemos logrado en Palos Verdes en estos casi ocho años. Lo que empezó en 2017, cuando entraron las primeras vacas, fue desde el principio un proyecto de vida: regenerar la tierra sin químicos y devolverle su biodiversidad. Ha sido un aprendizaje continuo — en 2020 montamos la huerta orgánica, entre 2022 y 2024 perseguimos la certificación orgánica, y en 2025 ingresamos a ACOGANAR. Lo que este documento propone es convertir ese cuidado ya probado en una marca de alimento de calidad y un estate de eventos en la sabana de Bogotá. No partimos de cero — partimos de una finca viva.",
    autor: "Olga Elizabeth Grijalba de Rodado · Fundadora, Finca Palos Verdes",
    retornos: [
      { nombre: "🌱 Natural", estado: "Alto", detalle: "MO 15,4%, 2,8 UGG/ha sin químicos (triple del promedio nacional), libre de brucelosis y TB, PUEAA + concesión de agua (Exp. CAR 97237)." },
      { nombre: "👥 Social", estado: "Medio", detalle: "Empleo + jornales + 10 jóvenes formados (RENASER) + red ACOGANAR." },
      { nombre: "✨ Inspiración", estado: "Alto", detalle: "Método replicable, libro en preparación, 38 años de la fundación familiar." },
      { nombre: "💰 Financiero", estado: "En déficit hoy", detalle: "Lo que esta inversión construye." },
    ],
    modeloHolistico: {
      resumen: "Inversión núcleo recomendada: ~US$218.000 (~COP 899 M) — ~22% del US$1M del planteamiento original. Break-even operativo Año 2; EBITDA acumulado positivo Año 2–3; EBITDA de crucero ~195 M/año (margen ~24%).",
      lineas: [
        { linea: "Pastoreo planificado holística (cercas móviles, agua a potreros, praderas)", usd: "18k", cop: "74", palanca: "↑ carga 19→~40 vientres sin comprar tierra", ingreso: "+35–50 M/año", payback: "~2 años" },
        { linea: "Cerdo de pastoreo (pie de cría, corrales móviles)", usd: "12k", cop: "50", palanca: "Caja mensual; mejora praderas", ingreso: "+12→+70 M/año", payback: "~2 años" },
        { linea: "Valor agregado — cortes (frío + desposte/empaque + marca + furgón)", usd: "60k", cop: "247", palanca: "9.750/kg → ~24.000/kg", ingreso: "+150–200 M/año", payback: "~3 años" },
        { linea: "Huerta orgánica intensiva (0,5 ha)", usd: "12k", cop: "50", palanca: "Frecuencia semanal; cliente cautivo", ingreso: "+43→+130 M/año", payback: "~2–3 años" },
        { linea: "Eventos de DÍA (bodas, alquiler, workshops; sin hotel)", usd: "40k", cop: "164", palanca: "Mayor margen por evento", ingreso: "+200–300 M/año", payback: "~2 años" },
        { linea: "PUEAA (compromisos CAR año a año)", usd: "21k", cop: "88", palanca: "Capital ambiental; de-risk eventos; obligatorio", ingreso: "Cumplimiento Exp. CAR 97237", payback: "—" },
        { linea: "Capital de trabajo 12–18 m + contingencia 10%", usd: "55k", cop: "226", palanca: "Cubre el Año 1", ingreso: "—", payback: "—" },
      ],
      total: { usd: "218k", cop: "899" },
      fueraDelNucleo: "Bombeo solar (US$15k, ahorro ~13 M/año, payback ~4,5 años) y hotel/alojamiento (capital intensivo, fase futura).",
    },
    pyl: {
      anios: ["Año 1", "Año 2", "Año 3", "Año 4", "Año 5"],
      filas: [
        { label: "Ingresos", valores: ["90", "330", "560", "720", "800"] },
        { label: "Costos directos", valores: ["-50", "-150", "-250", "-320", "-350"] },
        { label: "Nómina", valores: ["-40", "-80", "-120", "-150", "-165"] },
        { label: "Opex (incl. PUEAA ~13 M)", valores: ["-30", "-55", "-75", "-85", "-90"] },
        { label: "EBITDA", valores: ["-30", "+45", "+115", "+165", "+195"] },
        { label: "Margen", valores: ["-33%", "14%", "21%", "23%", "24%"] },
      ],
    },
    fincaCifras: [
      { dato: "Área", valor: "18,2 ha (Palos Verdes 12,7 + El Recuerdo 5,6); ~13 ha de pastoreo; laguna 1,8 ha", fuente: "Informe 2017" },
      { dato: "Hato", valor: "38 cabezas (ene-2026); núcleo ~19 vacas + toro DUMAS", fuente: "Inventario_Ganadero_38" },
      { dato: "Suelo", valor: "Andisoles, MO 15,4%, sin químicos desde 2017", fuente: "FUNDASES 2021; Informe 2017" },
      { dato: "Carga animal", valor: "2,8 UGG/ha (triple del promedio nacional)", fuente: "Guía Aforo" },
      { dato: "Precio de venta de res", valor: "9.750 COP/kg en pie (real, jul-2025)", fuente: "250704 Compra de Ganado" },
      { dato: "Agua", valor: "Concesión Río Subachoque 1,09 L/s + PUEAA (Construagro)", fuente: "Exp. CAR 97237" },
    ],
    cierre: "~US$218k (núcleo), por fases, para construir la pata financiera sobre tres retornos ya probados. El hotel y el bombeo solar quedan como decisiones separadas. El resultado: de activo regenerativo en déficit a un agronegocio diversificado con EBITDA de crucero ~195 M (24%) y equilibrio operativo en el Año 2-3.",
  },

  finanzas: {
    precios: [
      { concepto: "Res en pie (REAL)", valor: "$9.750/kg", tag: "verificado", fuente: "250704 Compra de Ganado" },
      { concepto: "Res en pie (brief)", valor: "$12.000/kg", tag: "modelado", fuente: "Brief p.5" },
      { concepto: "Cerdo gordo en pie (modelo)", valor: "$20.000/kg", tag: "modelado", fuente: "COSTOS CERDOS · L59" },
      { concepto: "Cerdo (brief)", valor: "$28.000/kg", tag: "modelado", fuente: "Brief p.6" },
      { concepto: "Canasta huerta (brief)", valor: "$60.000", tag: "modelado", fuente: "Brief p.7" },
      { concepto: "Forraje rollo Kikuyo", valor: "$220.000", tag: "verificado", fuente: "Fc 1622" },
      { concepto: "Transporte forraje/viaje", valor: "$370.000", tag: "verificado", fuente: "Fc 1530/1622" },
      { concepto: "Huerta retail — Fresa", valor: "$8.800/lb", tag: "verificado", fuente: "Precios Plaza 2025" },
      { concepto: "Huerta retail — Kale", valor: "$4.290/lb", tag: "verificado", fuente: "Precios Plaza 2025" },
      { concepto: "Huerta retail — Lechuga", valor: "$2.585/und", tag: "verificado", fuente: "Precios Plaza 2025" },
      { concepto: "Huerta retail — Huevo criollo", valor: "$920/und", tag: "verificado", fuente: "Precios Plaza 2025" },
      { concepto: "Energía bomba riego", valor: "$877/kWh (~$19.679/hora)", tag: "verificado", fuente: "Bombeo Solar PV 2025" },
    ],
    ventas: [
      { fecha: "04/07/2025", linea: "Res (en pie)", detalle: "6 terneros Angus (106,111,115,118,119,121)", precio: "$9.750/kg", total: "peso × 9.750", comprador: "P. Wilkie / R. Pombo", fuente: "250704 Compra de Ganado" },
      { fecha: "Año 2022", linea: "Huerta", detalle: "Facturación total (37 facturas)", precio: "~$49.000/factura", total: "$1.815.391", comprador: "Varios", fuente: "Facturas huerta" },
      { fecha: "—", linea: "Cerdo", detalle: "Sin ventas registradas", precio: "—", total: "$0", comprador: "—", fuente: "Censo ICA" },
      { fecha: "—", linea: "Eventos", detalle: "Sin ingresos registrados", precio: "—", total: "$0", comprador: "—", fuente: "—" },
    ],
    nomina: [
      { concepto: "Empleados en planilla", valor: "1", detalle: "Néstor Efraín Cañas R.", fuente: "Planilla abril (PILA)" },
      { concepto: "Salario básico", valor: "$2.600.000/mes", detalle: "brief: $2.000.000", fuente: "Nómina 1 agosto" },
      { concepto: "Auxilio transporte", valor: "$0", detalle: "no aplica (salario > tope)", fuente: "Nómina 1 abril" },
      { concepto: "Aportes patronales (PILA)", valor: "$651.200/mes", detalle: "~25% del salario", fuente: "Planilla abril" },
      { concepto: "Costo cargado/persona", valor: "~$3.470.000/mes", detalle: "brief: $3.500.000 ✓", fuente: "Cálculo PILA" },
      { concepto: "Costo laboral anual", valor: "~$40–42M", detalle: "brief: $126M (3 personas)", fuente: "Cálculo (1 empleado)" },
    ],
    costos: [
      { categoria: "Forraje", detalle: "10 rollos Kikuyo + transporte", valor: "$2.570.000", periodo: "feb-2025", tipo: "Factura" },
      { categoria: "Compost/pradera", detalle: "Lote de siembra (presupuesto)", valor: "$7.875.000", periodo: "s/f", tipo: "Presupuesto" },
      { categoria: "Mantenimiento", detalle: "Pintura/brochas", valor: "$303.700", periodo: "ene-2025", tipo: "Factura" },
      { categoria: "Riego (cotización)", detalle: "Tubería/aspersores", valor: "$801.800", periodo: "sep-2024", tipo: "Cotización" },
      { categoria: "Ambiental", detalle: "Tasa de seguimiento CAR", valor: "$159.205", periodo: "2024", tipo: "Factura" },
      { categoria: "Sanidad", detalle: "Pruebas brucelosis+TB (Servigan, 2×/año)", valor: "$1.910.000", periodo: "ene-2024", tipo: "Factura/Cotización" },
      { categoria: "Servicios", detalle: "Energía Enel (en mora)", valor: "$5.624.300", periodo: "sep-2024", tipo: "Factura" },
      { categoria: "Admin (ledger)", detalle: "Gastos admin/tributarios 2025", valor: "~$46.800.000", periodo: "2025", tipo: "Ledger" },
      { categoria: "Admin (ledger)", detalle: "Gastos admin/tributarios 2024", valor: "~$50.500.000", periodo: "2024", tipo: "Ledger" },
      { categoria: "Vehículo", detalle: "Mantenimiento Nissan Frontier (RAN039)", valor: "$4.168.000", periodo: "ago-2025", tipo: "Cotización" },
      { categoria: "Riego (energía)", detalle: "Bomba 25 HP eléctrica: ~$19.679/hora", valor: "$877/kWh", periodo: "ene-2025", tipo: "Estudio" },
    ],
    capex: [
      { linea: "Venue de eventos (cocina, baterías, carpa, séptico, deck ribera, servicios)", usd: "87.378", cop: "358,3M", cotizacion: "Investigado", nota: "Fase 2 · gatekeeper POT" },
      { linea: "Cuarto frío 10m³ + congelador + sala de desposte/empaque (+obra+INVIMA)", usd: "32.561", cop: "133,5M", cotizacion: "Investigado", nota: "Fase 1 (brief: 55k)" },
      { linea: "Escalado pecuario (cercas, agua, cerdos, FIV/TE, novillos, praderas)", usd: "30.195", cop: "123,8M", cotizacion: "Investigado", nota: "Fase 0" },
      { linea: "Capital de trabajo / opex pre-ingreso 12-18m", usd: "60.976", cop: "250,0M", cotizacion: "Parcial", nota: "Cubre Año 1 (-57M)" },
      { linea: "Contingencia 10%", usd: "20.446", cop: "83,8M", cotizacion: "—", nota: "3 cotiz./partida" },
      { linea: "Bombeo solar 10HP + cosecha aguas + RETIE", usd: "14.940", cop: "61,3M", cotizacion: "Investigado", nota: "Fase 0 · ahorra ~13M/año" },
      { linea: "Furgón refrigerado USADO 1,5-2t (Thermo King)", usd: "14.756", cop: "60,5M", cotizacion: "Investigado", nota: "Fase 1 (brief: 22k nuevo)" },
      { linea: "Marca + empaque + e-commerce + cadena de frío", usd: "12.439", cop: "51,0M", cotizacion: "Investigado", nota: "Fase 0" },
      { linea: "Huerta intensiva 0,5 ha (~60 canastas/sem, no 120)", usd: "12.195", cop: "50,0M", cotizacion: "Investigado", nota: "Fase 0 (brief: 65k)" },
    ],
    capexTotal: { usd: "285.899", cop: "1.172M", nota: "≈29% del brief" },
    pyl: {
      anios: ["Año 1", "Año 2", "Año 3", "Año 4", "Año 5"],
      filas: [
        { label: "Ingresos", valores: ["110", "484", "808", "1117", "1269"] },
        { label: "Costos directos", valores: ["-55", "-213", "-354", "-486", "-552"] },
        { label: "Nómina", valores: ["-42", "-95", "-160", "-220", "-260"] },
        { label: "Opex", valores: ["-70", "-110", "-150", "-185", "-205"] },
        { label: "EBITDA", valores: ["-57", "66", "144", "226", "252"] },
        { label: "Margen", valores: ["-51,8%", "13,6%", "17,8%", "20,2%", "19,9%"] },
      ],
    },
  },

  hato: {
    reconciliacion: [
      { indicador: "Cabezas (fiable, reciente)", verificado: "38", brief: "44", fuente: "Inventario_Ganadero_38 (ene-2026)" },
      { indicador: "Peso vivo total", verificado: "13.918 kg", brief: "16.000 kg", fuente: "Inventario_Ganadero_38 · O47" },
      { indicador: "Preñez (descarte feb-2025)", verificado: "~45% (9/20)", brief: "94%", fuente: "Vacas_para_Descarte (feb-2025)" },
      { indicador: "Preñez al destete (reciente)", verificado: "91% (nov-2025)", brief: "94%", fuente: "Chat de manejo — seguimiento de la dueña" },
      { indicador: "Ganancia diaria (hato)", verificado: "~0,50 kg/d", brief: "0,90 kg/d", fuente: "FINCA…ENERO 28 col S" },
      { indicador: "Ganancia diaria (terneros)", verificado: "1,0–1,6 kg/d", brief: "0,90 kg/d", fuente: "IDs 116/120/008" },
      { indicador: "Pureza Angus", verificado: "Registro Angus & Brangus (socio 1649); en absorción a puro", brief: "Angus puro", fuente: "Pesajes y chequeos final" },
      { indicador: "Toro reproductor", verificado: "DUMAS (LEP004) · 760 kg", brief: "—", fuente: "Inventario / web finca" },
      { indicador: "Carga animal", verificado: "2,8 UGG/ha (declarada); aforo 1,45 kg/m²", brief: "2,8 UGG/ha", fuente: "Guía Aforo" },
    ],
    sanidad: [
      { item: "Brucelosis", estado: "Confirmado", detalle: "Cert. 0001270553-24BR. Único reactor (animal #44) confirmado NEGATIVO por fluorescencia polarizada (reporte ICA 220-2024)", vigencia: "21/08/2024 → 05/08/2025 (renovar)", fuente: "Certificado predio libre brucelosis; 220-2024" },
      { item: "Tuberculosis", estado: "Confirmado", detalle: "Certificación ICA N° 0001270553-24TB (Servigan Sabana); 54 Angus negativos", vigencia: "07/08/2024 → 12/07/2025 (renovar)", fuente: "Certificado predio libre tuberculosis" },
      { item: "Vacunación", estado: "Confirmado", detalle: "Aftosa 38 dosis + brucelosis (ciclo 2026)", vigencia: "04/06/2026", fuente: "PVPP-9582684 FEDEGAN/ICA" },
    ],
    inventarioTiempo: [
      { fecha: "18-may-2024", total: "~34+", vientres: "24", toro: "1", crias: "8 lactantes + 18 levante", fuente: "Informe mayo" },
      { fecha: "06-ago-2024", total: "~40", vientres: "25", toro: "1", crias: "8 + 7", fuente: "Informe 6 agosto" },
      { fecha: "09-jul-2024 (censo TB)", total: "54", vientres: "38 H", toro: "—", crias: "16 M", fuente: "Tuberculosis" },
      { fecha: "24-feb-2025", total: "47", vientres: "23", toro: "1", crias: "24 crías", fuente: "LISTA…2038" },
      { fecha: "01-ene-2026", total: "38", vientres: "18", toro: "1", crias: "~19", fuente: "Inventario_38" },
      { fecha: "jun-2026 (brief)", total: "44", vientres: "—", toro: "—", crias: "—", fuente: "Brief editorial (cifra de presentación, no conciliada)" },
    ],
  },

  diagnostico: {
    tiene: [
      { activo: "Hato", estado: "38 cabezas (corte 1-ene-2026): 1 toro Angus puro registrado (Dumas/LEP004, 760 kg), 18 vientres Angus, ~19 terneros/levante · ~13,9 t de peso vivo", fuente: "Inventario_Ganadero_38" },
      { activo: "Tierra", estado: "21,4 ha (Palos Verdes 16 ha + El Recuerdo 5,4 ha); avalúo catastral conjunto $4.328 M", fuente: "Impuesto Palos Verdes, Predial El Recuerdo" },
      { activo: "Genética", estado: "Angus comercial en absorción a puro; un reproductor puro registrado; trazabilidad individual", fuente: "Listas y registros" },
      { activo: "Certificaciones", estado: "Orgánica (huerta) · Libre de TB · Libre de brucelosis (venció ago-2025 → renovar) · Vacunación aftosa al día (jun-2026) · Proyecto de carbono (Carbono Local+/Verra)", fuente: "Certificados ICA, cert. orgánica" },
      { activo: "Agua", estado: "Concesión del río Subachoque + contador + PUEAA (CAR) — de las pocas fincas que cumple todos los requisitos", fuente: "PUEAA, RT_FACTURAS (CAR)" },
      { activo: "Equipo", estado: "1 empleado formal (Néstor Cañas, técnico orgánico)", fuente: "Nómina, planilla" },
    ],
    financiero: [
      "Ingresos reales mínimos e intermitentes: huerta $1,8 M en 2022 (único año documentado) y 1 venta de ganado (jul-2025, sin peso ni total documentado). El negocio no se autofinancia con ventas.",
      "Costos dominados por estructura corporativa: el ledger de Construagro mueve ~45–55 M/año, mayormente overhead del holding, no costo directo de finca.",
      "Costo directo de finca (estimado) ~$60–80 M/año: nómina ~40 M, forraje ~5–15 M, prediales ~9,4 M, energía con mora acumulada ~$13 M, sanidad/riego/jornales puntuales.",
      "Resultado: déficit operativo estructural (estimado) ≈ −$50 a −75 M/año, financiado por la familia/Construagro. El valor está en el activo (tierra ~$4.328 M + hato Angus ~13,9 t), no en el flujo.",
    ],
    infoFaltante: {
      p1: [
        "Extracto bancario operativo de la finca (cuenta dedicada, separado del libro del holding) — 24 meses de movimientos.",
        "Cuantificar ventas anuales de ganado (cabezas, kilos, valor) — hoy consta una sola venta sin peso ni total.",
        "Consolidar el costo directo anualizado (alimento, combustible/maquinaria, sanidad veterinaria, jornales).",
      ],
      p2: [
        "Facturación de la huerta 2023–2025 (solo existe 2022).",
        "Consolidar pasivos y deuda (mora energía ~$13 M, proveedores, impuestos vehiculares ~$10,8 M).",
        "Aclarar la titularidad de la tierra — los prediales figuran a nombre de terceros (Gaviria; Vargas Gil).",
      ],
      p3: [
        "Reconstruir el libro de movimientos del hato (altas y bajas) que concilie el inventario (54→47→38).",
        "Cerrar el caso del positivo de brucelosis (#44) con segregación, retesteo o descarte documentado; renovar certificación.",
        "Corregir el cálculo de preñez e IEP (hoja de reproducción con fórmulas erróneas).",
      ],
    },
    oportunidades: [
      "Valor agregado en la carne — de en pie $9.750/kg a cortes propios $24.000/kg: +$1,5–2 M neto/res.",
      "Elevar la carga sin comprar tierra (Savory) — subir el aforo de 1,45 a la meta de 6 kg/m² con pastoreo planificado.",
      "Carbono — proyecto Carbono Local+/Verra sobre suelo regenerativo: ingreso ambiental adicional.",
      "Agua / CAR / PUEAA — el cumplimiento de-risquea permisos (incl. eventos) y posiciona la finca como modelo regenerativo.",
      "Eventos de día — bodas, alquiler de espacio, talleres (el hotel es una inversión separada y futura).",
      "Genética Angus — la absorción a puro habilita venta de pie de cría premium.",
      "Integración cerdos/compost — proyectada (no incurrida); cierra ciclos de nutrientes.",
    ],
  },

  certificaciones: [
    { tema: "Orgánico (huerta)", estado: "Real", detalle: "Mayacert 2023-034 · ~70 cultivos hortícolas. NO certifica la carne.", vigencia: "16/08/2023 → venció 16/08/2024", fuente: "SEN-COV2" },
    { tema: "Libre de brucelosis", estado: "Confirmado", detalle: "ICA 0001270553-24BR", vigencia: "→ 05/08/2025", fuente: "Certificado predio libre brucelosis" },
    { tema: "Libre de tuberculosis", estado: "Confirmado", detalle: "Certificación ICA de predio libre de TB N° 0001270553-24TB (54 Angus negativos)", vigencia: "07/08/2024 → 12/07/2025", fuente: "Certificado predio libre tuberculosis" },
    { tema: "Sin químicos desde 2017", estado: "Respaldado", detalle: "Estudio agroecológico jul-2017 (Ing. Guido Carrillo) + insumos solo ecológicos (FUNDASES 2021)", vigencia: "2017 →", fuente: "Informe Palos Verdes Julio 2017" },
    { tema: "Método agroecológico", estado: "Verificado", detalle: "Análisis FUNDASES S7-88-2021: MO 15,4%, pH 5,4; recomienda compost, roca fosfórica, EM", vigencia: "may-2021", fuente: "Recomendación agronómica S7-88-2021" },
    { tema: "ACOGANAR", estado: "Afiliación/candidato", detalle: "Gremio de ganadería regenerativa; 'Aval de Confianza' (≥70% en 6 pilares) por obtener", vigencia: "2025", fuente: "Aval de Confianza" },
    { tema: "'Replicado en 10 fincas'", estado: "Impreciso", detalle: "En realidad 10 jóvenes en parcelas de 1 ha (piloto RENASER 'Suelo Vivo–Vida Sana')", vigencia: "2020-21", fuente: "ConceptNote Renaser" },
    { tema: "Construagro S.A.S.", estado: "Vigente", detalle: "NIT 860.520.662-7 · desde 1984 · gerente Olga E. Grijalba", vigencia: "—", fuente: "CCB / RUT" },
    { tema: "Mejora genética (plan)", estado: "Propuesta", detalle: "BIOTEGAN S.A.S.: producción de embriones in vitro (FIV) y transferencia para acelerar pureza/genética Angus", vigencia: "oct-2025", fuente: "Propuesta de trabajo por preñez" },
    { tema: "Plan de agua (PUEAA)", estado: "Vigente", detalle: "Plan de Uso Eficiente y Ahorro de Agua + estudio de bombeo solar para riego", vigencia: "2025", fuente: "Informe Final PUEAA 2025" },
    { tema: "Proyecto de carbono", estado: "Oportunidad", detalle: "Carbono Local+ (Verra ID 3927, VCS+CCB, VM0042) — potencial 5ª línea de ingreso. Confirmar vinculación formal del predio.", vigencia: "2023", fuente: "Roll-up Carbono Local+ NP 2023" },
  ],

  pendientes: {
    alta: [
      { doc: "Libro de movimientos del hato (altas y bajas)", motivo: "Conciliar el conteo: cada animal con fecha de entrada y salida. Es el documento que falta para explicar 44 vs 38." },
      { doc: "Guías de movilización ICA (SINIGAN) + bonos de venta", motivo: "Probar cada salida del hato. Solo existe la guía de jul-2025 (6 terneros)." },
      { doc: "Inventario oficial fechado y firmado, con desglose por clase", motivo: "Fijar LA cifra de referencia del brief a una fecha de corte." },
      { doc: "Renovación cert. orgánica Mayacert (post ago-2024)", motivo: "Sostener 'huerta orgánica certificada' en 2026." },
      { doc: "Renovación brucelosis (vence 05/08/2025)", motivo: "Mantener estatus sanitario." },
      { doc: "Cotizaciones reales de capex (cuarto frío, furgón, venue, huerta)", motivo: "Respaldar el uso de US$1,0M." },
      { doc: "Registro sanitario / INVIMA del desposte", motivo: "Vender carne despostada legalmente." },
      { doc: "Extracto bancario operativo de la finca", motivo: "Reconstruir ingresos/costos directos." },
      { doc: "Títulos de propiedad de la tierra + cadena histórica", motivo: "Definir qué entra a la operación." },
      { doc: "Licencias de uso del suelo / POT para eventos", motivo: "Línea de eventos (53% del ingreso Año 5)." },
    ],
    media: [
      { doc: "Registro completo de partos y de mortalidad", motivo: "Documentar las altas (nacimientos) y bajas (muertes) que mueven el conteo." },
      { doc: "Certificado ICA de predio libre de tuberculosis", motivo: "Afirmar 'libre de TB'." },
      { doc: "Planta de sacrificio autorizada (nombre/tarifa)", motivo: "Línea de carne." },
      { doc: "Facturas de venta de ganado 2026", motivo: "Validar precio del brief ($12.000/kg)." },
      { doc: "Facturas de alimento, combustible, veterinaria, jornales", motivo: "Calcular costo directo real." },
      { doc: "Chequeo reproductivo 2026 con conteo", motivo: "Sostener % de preñez actual." },
    ],
  },
};
